name: AddRecipe
main: io.github.plugin.addrecipe.AddRecipe
version: 1.16
api-version: 1.16
author: RANK0816
commands:
  addrecipe:
    permission: op
    permission-message: "You must have permission to use this command!"
  recipelist:
